### ISSUE TITLE
Open the app using deep links

### ISSUE THREAD

**Issue by bennyboer** [bennyboer/bbb_app#22]
We need to use so called "deep links" that allow us to specify a specific URI scheme for our app (for example `bbb-app://HOST`). Those can be registered for Android and iOS to open our app and automatically insert the proper meeting URL and even the access code!

There is a plugin for Flutter available: https://github.com/avioli/uni_links

## TODO

- [x] Create prototype for deep linking with Android -> App should be opened by link
- [x] Support automatically inserting the correct meeting URL from the link in the start view
- [x] Support automatically inserting the access code from the link (when the meeting is secured by an access code, so this must be optional)
